require 'rubygems'
require 'topcgen/runner'
require 'topcgen/settings'
require 'topcgen/browser'
require 'topcgen/http'
require 'topcgen/cookie_store'
require 'topcgen/tc_search'
require 'topcgen/tc_detail'
